config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/proprietarios')
  resources :veiculos
  resources :proprietarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proprietario.rb
class Proprietario < ApplicationRecord
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  validates_presence_of :placa, :message => " - Deve ser preenchido"
  validates_presence_of :renavam, :message => " - Deve ser preenchido"
  belongs_to :proprietario

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proprietarios_controller.rb
class ProprietariosController < ApplicationController
  before_action :set_proprietario, only: %i[ show edit update destroy ]

  # GET /proprietarios or /proprietarios.json
  def index
    @proprietarios = Proprietario.all
  end

  # GET /proprietarios/1 or /proprietarios/1.json
  def show
  end

  # GET /proprietarios/new
  def new
    @proprietario = Proprietario.new
  end

  # GET /proprietarios/1/edit
  def edit
  end

  # POST /proprietarios or /proprietarios.json
  def create
    @proprietario = Proprietario.new(proprietario_params)

    respond_to do |format|
      if @proprietario.save
        format.html { redirect_to @proprietario, notice: "Proprietario foicriado com sucesso." }
        format.json { render :show, status: :created, location: @proprietario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proprietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proprietarios/1 or /proprietarios/1.json
  def update
    respond_to do |format|
      if @proprietario.update(proprietario_params)
        format.html { redirect_to @proprietario, notice: "Proprietario foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @proprietario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proprietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proprietarios/1 or /proprietarios/1.json
  def destroy
    @proprietario.destroy
    respond_to do |format|
      format.html { redirect_to proprietarios_url, notice: "Proprietario foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proprietario
      @proprietario = Proprietario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proprietario_params
      params.require(:proprietario).permit(:cpf_cnpj, :nome, :endereco)
    end
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: %i[ show edit update destroy ]

  # GET /veiculos or /veiculos.json
  def index
    @veiculos = Veiculo.all
  end

  # GET /veiculos/1 or /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos or /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to @veiculo, notice: "Veiculo foi criado com sucesso." }
        format.json { render :show, status: :created, location: @veiculo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1 or /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to @veiculo, notice: "Veiculo foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @veiculo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1 or /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: "Veiculo foi apagado com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def veiculo_params
      params.require(:veiculo).permit(:placa, :renavam, :proprietario_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proprietarios_helper.rb
module ProprietariosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proprietario</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  </div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/proprietarios">Proprietarios</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/veiculos">Veiculos</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

<br>

  <footer>
    <div class="container">
      ®Crud Detran  <%= Time.now.ctime %>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/proprietarios/_form.html.erb
<%= form_with(model: proprietario, local: true) do |form| %>
  <% if proprietario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proprietario.errors.count, "error") %> prohibited this proprietario from being saved:</h2>

      <ul>
        <% proprietario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cpf_cnpj %>
    <%= form.text_field :cpf_cnpj %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proprietarios/edit.html.erb
<h1>Editando Proprietario</h1>

<%= render 'form', proprietario: @proprietario %>

<%= link_to 'Mostrar', @proprietario %> |
<%= link_to 'Voltar', proprietarios_path %>

app/views/proprietarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proprietarios</h1>

<table>
  <thead>
    <tr>
      <th>Cpf-Cnpj</th>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Ação</th>
      <th>Ação</th>
      <th>Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @proprietarios.each do |proprietario| %>
      <tr>
        <td><%= proprietario.cpf_cnpj %></td>
        <td><%= proprietario.nome %></td>
        <td><%= proprietario.endereco %></td>
        <td><%= link_to 'Mostrar', proprietario %></td>
        <td><%= link_to 'Editar', edit_proprietario_path(proprietario) %></td>
        <td><%= link_to 'Apagar', proprietario, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Adicionar proprietario', new_proprietario_path %>

app/views/proprietarios/new.html.erb
<h1>Novo Proprietario</h1>

<%= render 'form', proprietario: @proprietario %>

<%= link_to 'Voltar', proprietarios_path %>

app/views/proprietarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpf ou cnpj:</strong>
  <%= @proprietario.cpf_cnpj %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @proprietario.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @proprietario.endereco %>
</p>

<%= link_to 'Editar', edit_proprietario_path(@proprietario) %> |
<%= link_to 'Voltar', proprietarios_path %>

app/views/veiculos/_form.html.erb
<%= form_with(model: veiculo, local: true) do |form| %>
  <% if veiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(veiculo.errors.count, "error") %> seu veiculo não pode ser salvo pois:</h2>

      <ul>
        <% veiculo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :placa,"Placa :"%>
    <%= form.text_field :placa,maxlength:7 %>
  </div>

  <div class="field">
    <%= form.label :renavam,"Renavam :"%>
    <%= form.text_field :renavam, maxlength: 11 %>
  </div>

    <div class="field">
      <%= form.label :proprietario,"Proprietario:" %>
      <%= collection_select(:veiculo, :proprietario_id, Proprietario.all , :id, :nome) %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/veiculos/edit.html.erb
<h1>Editando Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>

<%= link_to 'Mostrar', @veiculo %> |
<%= link_to 'Voltar', veiculos_path %>

app/views/veiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Veiculos</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Renavam</th>
      <th>Proprietario</th>
      <th> Acao</th>
      <th> Acao</th>
      <th> Acao</th>
    </tr>
  </thead>

  <tbody>
    <% @veiculos.each do |veiculo| %>
      <tr>
        <td><%= veiculo.placa %></td>
        <td><%= veiculo.renavam %></td>
        <td><%= veiculo.proprietario.nome %></td>
        <td><%= link_to 'Mostrar', veiculo %></td>
        <td><%= link_to 'Editar', edit_veiculo_path(veiculo) %></td>
        <td><%= link_to 'Apagar', veiculo, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Veiculo', new_veiculo_path %>

app/views/veiculos/new.html.erb
<h1>Novo Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>

<%= link_to 'Voltar', veiculos_path %>

app/views/veiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @veiculo.placa %>
</p>

<p>
  <strong>Renavam:</strong>
  <%= @veiculo.renavam %>
</p>

<p>
  <strong>Proprietario:</strong>
  <%= @veiculo.proprietario.nome %>
</p>

<%= link_to 'Editar', edit_veiculo_path(@veiculo) %> |
<%= link_to 'Voltar', veiculos_path %>